FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY app ./app
RUN npm run build
FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/package.json ./
EXPOSE 3000
CMD ["npm","start"]
