import 'reflect-metadata';
import { Body, Controller, Get, Headers, HttpException, HttpStatus, Injectable, Module, OnModuleInit, Param, Post } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { Pool, PoolClient } from 'pg';
import { createClient } from 'redis';

const pool = new Pool({ connectionString: process.env.DATABASE_URL || 'postgres://knb:knb@localhost:5432/knb' });
const redis = createClient({ url: process.env.REDIS_URL || 'redis://localhost:6379' });

@Injectable()
class AppService implements OnModuleInit {
  async onModuleInit() { try { await redis.connect(); } catch { /* Redis is auxiliary; PostgreSQL remains authoritative. */ } }
  async health() { let database = 'ok', cache = 'ok'; try { await pool.query('SELECT 1'); } catch { database = 'error'; } try { if (!redis.isReady) cache = 'unavailable'; } catch { cache = 'error'; } return { status: database === 'ok' ? 'ok' : 'degraded', environment: 'SANDBOX', realMoney: false, database, cache }; }
  async assets() { return (await pool.query('SELECT code,kind,scale,is_active AS "isActive" FROM assets WHERE is_active=true ORDER BY code')).rows; }
  async accounts(ownerId?: string) { return (await pool.query('SELECT a.id,a.owner_id AS "ownerId",s.code AS asset,a.status FROM accounts a JOIN assets s ON s.id=a.asset_id WHERE ($1::text IS NULL OR a.owner_id=$1) ORDER BY a.created_at', [ownerId || null])).rows; }
  async createAccount(body: any) { if (!body?.ownerId || !body?.asset) throw new HttpException('ownerId and asset are required', 400); const r = await pool.query('INSERT INTO accounts(owner_id,asset_id) SELECT $1,id FROM assets WHERE code=$2 AND is_active=true ON CONFLICT (owner_id,asset_id,account_type) DO UPDATE SET owner_id=EXCLUDED.owner_id RETURNING id,owner_id AS "ownerId",$2 AS asset,status', [body.ownerId, body.asset]); if (!r.rowCount) throw new HttpException('unknown asset', 400); return r.rows[0]; }
  async balance(id: string) { const r = await pool.query('SELECT COALESCE(SUM(e.amount),0)::text AS balance, s.code AS asset FROM ledger_entries e JOIN assets s ON s.id=e.asset_id WHERE e.account_id=$1 GROUP BY s.code', [id]); return r.rows[0] || { balance: '0', asset: null }; }
  async post(body: any, actorId: string, idem: string) { if (!idem) throw new HttpException('Idempotency-Key header is required', 400); const entries = body?.entries; if (!Array.isArray(entries) || entries.length < 2) throw new HttpException('at least two entries are required', 400); const client = await pool.connect(); try { await client.query('BEGIN'); const existing = await client.query('SELECT id,status,reason FROM ledger_transactions WHERE idempotency_key=$1 FOR SHARE', [idem]); if (existing.rowCount) { await client.query('COMMIT'); return existing.rows[0]; } const sums = new Map<string,bigint>(); for (const e of entries) { if (!e.accountId || !e.asset || !/^-?\d+$/.test(String(e.amount)) || BigInt(e.amount) === 0n) throw new HttpException('invalid entry', 400); const a = await client.query('SELECT id,asset_id FROM accounts a JOIN assets s ON s.id=a.asset_id WHERE a.id=$1 AND s.code=$2 AND a.status=\'ACTIVE\'', [e.accountId,e.asset]); if (!a.rowCount) throw new HttpException('invalid account or asset mismatch', 400); sums.set(e.asset,(sums.get(e.asset)||0n)+BigInt(e.amount)); } for (const [asset,sum] of sums) if (sum !== 0n) throw new HttpException(`unbalanced asset: ${asset}`, 400); const tx = await client.query('INSERT INTO ledger_transactions(idempotency_key,actor_id,status) VALUES($1,$2,\'POSTED\') RETURNING id,status', [idem,actorId]); for (const e of entries) { const a = await client.query('SELECT asset_id FROM accounts WHERE id=$1',[e.accountId]); await client.query('INSERT INTO ledger_entries(transaction_id,account_id,asset_id,amount) VALUES($1,$2,$3,$4)', [tx.rows[0].id,e.accountId,a.rows[0].asset_id,e.amount]); } await client.query('INSERT INTO audit_logs(actor_id,action,resource,result,metadata) VALUES($1,\'create_transaction\',$2,\'SUCCESS\',$3)', [actorId,tx.rows[0].id,JSON.stringify({environment:'SANDBOX'})]); await client.query('COMMIT'); return tx.rows[0]; } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
}
@Controller()
class AppController { constructor(private readonly app: AppService) {} @Get('health') health(){return this.app.health();} @Get('assets') assets(){return this.app.assets();} @Get('accounts') accounts(@Headers('x-owner-id') owner?:string){return this.app.accounts(owner);} @Post('accounts') create(@Body() b:any){return this.app.createAccount(b);} @Get('accounts/:id/balance') balance(@Param('id') id:string){return this.app.balance(id);} @Post('transactions') post(@Body() b:any,@Headers('x-actor-id') actor='sandbox-user',@Headers('idempotency-key') key=''){return this.app.post(b,actor,key);} }
@Module({controllers:[AppController],providers:[AppService]}) class AppModule {}
async function main(){ const app=await NestFactory.create(AppModule); app.enableCors(); app.useGlobalPipes(new (require('@nestjs/common').ValidationPipe)({transform:true,whitelist:false})); await app.listen(Number(process.env.PORT||3001),'0.0.0.0'); }
main();
